 -- Bootstrap minimal sales tables if missing
 CREATE TABLE IF NOT EXISTS sales_pipelines (
   id TEXT PRIMARY KEY,
   name TEXT NOT NULL,
   createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
   updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
 );
ALTER TABLE sales_pipelines ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE sales_pipelines ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW();
 
 CREATE TABLE IF NOT EXISTS sales_stages (
   id TEXT PRIMARY KEY,
   pipeline_id TEXT REFERENCES sales_pipelines(id) ON DELETE CASCADE,
   name TEXT NOT NULL,
   order_index INT NOT NULL DEFAULT 0,
   probability INT NOT NULL DEFAULT 0,
   createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
   updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
 );
ALTER TABLE sales_stages ADD COLUMN IF NOT EXISTS order_index INT NOT NULL DEFAULT 0;
ALTER TABLE sales_stages ADD COLUMN IF NOT EXISTS probability INT NOT NULL DEFAULT 0;
ALTER TABLE sales_stages ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE sales_stages ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW();
 
 CREATE TABLE IF NOT EXISTS sales_deals (
   id TEXT PRIMARY KEY,
   name TEXT NOT NULL,
   amount NUMERIC(14,2) NOT NULL DEFAULT 0,
   currency TEXT NOT NULL DEFAULT 'THB',
   pipeline_id TEXT REFERENCES sales_pipelines(id) ON DELETE SET NULL,
   stage_id TEXT REFERENCES sales_stages(id) ON DELETE SET NULL,
   owner_id TEXT,
   client_id TEXT,
   client_org TEXT,
   status TEXT NOT NULL DEFAULT 'open',
   probability INT NOT NULL DEFAULT 0,
   createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
   updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
 );
ALTER TABLE sales_deals ADD COLUMN IF NOT EXISTS amount NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE sales_deals ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'THB';
ALTER TABLE sales_deals ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'open';
ALTER TABLE sales_deals ADD COLUMN IF NOT EXISTS probability INT NOT NULL DEFAULT 0;
ALTER TABLE sales_deals ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE sales_deals ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW();
